README.md
config/control-plane-components.yaml
config/rbac/role.yaml
controllers/kamajicontrolplane_controller_cluster_patch.go
docs/providers-kubevirt.md

KubeVirt support

---

.github/workflows/release.yaml

Automatic creation of a release

---

README.md
config/control-plane-components.yaml
config/rbac/role.yaml
controllers/kamajicontrolplane_controller_cluster_patch.go
docs/providers-metal3.md

Metal³ support

---

config/control-plane-components.yaml
config/default/kustomization.yaml

chore(kustomize): adding cluster.x-k8s.io/provider label to components

---

config/control-plane-components.yaml
config/rbac/role.yaml
controllers/kamajicontrolplane_controller_cluster_patch.go

RBAC fixes and code optimization

---

.gitignore

chore(gitignore): ignoring .tiltbuild

---

api/v1alpha1/kamajicontrolplane_types.go
config/control-plane-components.yaml
config/crd/bases/controlplane.cluster.x-k8s.io_kamajicontrolplanes.yaml

chore(kustomize): supporting scale subresource

---

README.md
config/control-plane-components.yaml
config/rbac/role.yaml
controllers/kamajicontrolplane_controller_cluster_patch.go
controllers/kamajicontrolplane_controller_cluster_patch_errors.go
docs/providers-vsphere.md

vSphere support

---

README.md
controllers/kamajicontrolplane_controller_resources.go

Ignoring CA replication if backed by the Kamaji operator

---

api/v1alpha1/kamajicontrolplane_types.go
config/control-plane-components.yaml
config/crd/bases/controlplane.cluster.x-k8s.io_kamajicontrolplanes.yaml
controllers/kamajicontrolplane_controller.go

Increasing error visibility in the KamajiControlPlane Status sub-resource

---

controllers/kamajicontrolplane_controller_tcp.go
go.mod
go.sum

fix(kamaji): scale to zero kamajicontrolplane resources

---

controllers/kamajicontrolplane_controller_tcp.go

fix(addons): coredns should be allowed even with no options

---

api/v1alpha1/kamajicontrolplane_types.go
config/control-plane-components.yaml
config/crd/bases/controlplane.cluster.x-k8s.io_kamajicontrolplanes.yaml

Fix for https://github.com/clastix/cluster-api-control-plane-provider-kamaji/issues/64

Updated descriptions to match the current version syntax requirements

---

api/v1alpha1/kamajicontrolplane_types.go
config/control-plane-components.yaml
config/crd/bases/controlplane.cluster.x-k8s.io_kamajicontrolplanes.yaml

Support for additional printer columns

---

README.md
config/control-plane-components.yaml
config/rbac/role.yaml
controllers/kamajicontrolplane_controller_cluster_patch.go
docs/providers-aws.md

AWS support

---

README.md
config/control-plane-components.yaml
config/rbac/role.yaml
controllers/kamajicontrolplane_controller_cluster_patch.go
docs/providers-tinkerbell.md

Closes #8.
Just a minor review from you would be great, @EntraptaJ @chrisdoherty4

Tinkerbell support

---

controllers/kamajicontrolplane_controller.go
main.go

feat: max concurrent reconciles flag

---

README.md
docs/providers-openstack.md

docs: openstack support

---

config/control-plane-components.yaml
config/manager/manager.yaml

This provides an easy way to configure the feature gates when installing the provider.

feat: Add feature gates to manifest

---

controllers/kamajicontrolplane_controller_externalreference.go

remove List KamajiControlPlanes call

---

controllers/kamajicontrolplane_controller_externalreference.go

Missed styling guide for changes introduced with #132

style: aligning to gci linting options

---

controllers/kamajicontrolplane_controller.go

Resolves #133
Instead of only waiting that "tcp.Status.Kubernetes.Version.Status" is different than nil to set the 'initialized' status, wait that its value is Ready.
As the 'initialized' status should not be unset after being set, only do this check if the 'initialized' status has not been set

fix: Report status initialized only if the TenantControlPlane have been ready once

---

controllers/externalclusterreference_controller.go

fix(ecr): ignoring controllers used names

---

api/v1alpha1/kamajicontrolplane_types.go
config/control-plane-components.yaml
config/crd/bases/controlplane.cluster.x-k8s.io_kamajicontrolplanes.yaml
config/crd/bases/controlplane.cluster.x-k8s.io_kamajicontrolplanetemplates.yaml

fix: dns service ips are automatically inflected by kamaji

---

controllers/kamajicontrolplane_controller_tcp.go

fix: cluster network is optional

---

config/control-plane-components.yaml
config/rbac/role.yaml
controllers/kamajicontrolplane_controller_cluster_patch.go

fix: missing list and watch RBAC of unstructured objects

---

templates/vsphere/capi-kamaji-vsphere-autoscaler-template.yaml
templates/vsphere/capi-kamaji-vsphere-class-template.yaml
templates/vsphere/capi-kamaji-vsphere-dhcp-template.yaml
templates/vsphere/capi-kamaji-vsphere-template-ccm.yaml
templates/vsphere/capi-kamaji-vsphere-template-csi.yaml
templates/vsphere/capi-kamaji-vsphere-template.yaml

add vsphere sample templates

---

templates/proxmox/capi-kamaji-proxmox-class.yaml
templates/proxmox/capi-kamaji-proxmox-template.yaml

add proxmox templates

---

templates/proxmox/capi-kamaji-proxmox-template.yaml

add node pool variable in proxmox template

fix(docs): add node pool variable in proxmox template
