api/v1alpha1/kamajicontrolplane_conditions.go
api/v1alpha1/kamajicontrolplane_types.go
api/v1alpha1/zz_generated.deepcopy.go
config/control-plane-components.yaml
config/crd/bases/controlplane.cluster.x-k8s.io_kamajicontrolplanes.yaml
controllers/conditions.go
controllers/kamajicontrolplane_controller.go

Closes #52.
This will remove any chance of getting stuck with unrecoverable clusters due to the error status handling.
Rather, a set of conditions will be reported as it follows:
```yaml
status:
conditions:
- lastTransitionTime: "2023-09-22T08:24:25Z"
message: ""
reason: Completed
status: "True"
type: TenantControlPlaneCreated
- lastTransitionTime: "2023-09-22T08:24:54Z"
message: ""
reason: Completed
status: "True"
type: TenantcontrolPlaneAddressReady
- lastTransitionTime: "2023-09-22T08:25:40Z"
message: ""
reason: Completed
status: "True"
type: InfrastructureClusterPatched
- lastTransitionTime: "2023-09-22T08:25:47Z"
message: ""
reason: Completed
status: "True"
type: KamajiControlPlaneIsInitialized
- lastTransitionTime: "2023-09-22T08:25:51Z"
message: ""
reason: Completed
status: "True" …
```

Supporting KamajiControlPlane conditions

---

api/v1alpha1/kamajicontrolplane_conditions.go
api/v1alpha1/kamajicontrolplane_types.go
config/control-plane-components.yaml
config/crd/bases/controlplane.cluster.x-k8s.io_kamajicontrolplanes.yaml
controllers/conditions.go
controllers/kamajicontrolplane_controller.go
controllers/kamajicontrolplane_controller_resources.go

Closes #66.
@jds9090 I tried to summarize the state transitions in the following YAML, let me know what do you think.
```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KamajiControlPlane
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"controlplane.cluster.x-k8s.io/v1alpha1","kind":"KamajiControlPlane","metadata":{"annotations":{},"creationTimestamp":"2023-10-12T10:16:00Z","generation":2,"labels":{"cluster.x-k8s.io/cluster-name":"capi-quickstart"},"name":"capi-quickstart-kubevirt","namespace":"default","ownerReferences":[{"apiVersion":"cluster.x-k8s.io/v1beta1","blockOwnerDeletion":true,"controller":true,"kind":"Cluster","name":"capi-quickstart","uid":"913044ea-5135-4a61-a230-f07132d9ea04"}],"resourceVersion":"4317317","uid":"c8943729 …
```

Refactoring KamajiControlPlane Ready status report

---

README.md
config/control-plane-components.yaml
config/rbac/role.yaml
controllers/kamajicontrolplane_controller_cluster_patch.go
docs/providers-nutanix.md

close #10 
Add Nutanix CAPX suppor to Kamaji CAPI Provider

Nutanix support

---

README.md
config/control-plane-components.yaml
config/rbac/role.yaml
controllers/kamajicontrolplane_controller_cluster_patch.go
docs/providers-hetzner.md

Closes #33.
Can be merged once github.com/syself/cluster-api-provider-hetzner v1.0.0-beta.18 is released.

Hetzner support

---

controllers/kamajicontrolplane_controller_cluster_patch.go
controllers/kamajicontrolplane_controller_cluster_patch_errors.go

Patching the controlPlaneEndpoint in the VSphere cluster was broken due to a bad comparison (Is instead of As, so comparing the error contents instead of the error type). This PR fixes that.
I also fixed a typo in the error message itself.

fix: patchCluster not working on vsphere

---

controllers/kamajicontrolplane_controller_resources.go
controllers/kamajicontrolplane_controller_tcp.go

During reconciliation, the control plane provider copies the content from the secret provided by Kamaji, named <cluster>-admin-kubeconfig, into a generic Cluster API secret, <cluster>-kubeconfig, which can then be used by the bootstrap provider and other cluster components.
This change introduces a new annotation, kamaji.clastix.io/kubeconfig-secret-key, for the KamajiControlPlane resource. This annotation instructs the control plane provider to read the kubeconfig from a specific key (the default one is admin.conf).
Example:
```
kamaji.clastix.io/kubeconfig-secret-key: super-admin.svc
```
This will instruct the system to use `super-admin.svc` a kubeconfig with a local service FQDN (introduced by https://github.com/clastix/kamaji/pull/403).
And also copy this annotation for …

Allow overriding secretKey for kubeconfig

---

Dockerfile

Fix regression introduced by https://github.com/clastix/cluster-api-control-plane-provider-kamaji/pull/93
Without this build fails:
```
go fmt ./...
go vet ./...
test -s /Users/kvaps/git/cluster-api-control-plane-provider-kamaji/bin/setup-envtest || GOBIN=/Users/kvaps/git/cluster-api-control-plane-provider-kamaji/bin go install sigs.k8s.io/controller
-runtime/tools/setup-envtest@latest
KUBEBUILDER_ASSETS="/Users/kvaps/git/cluster-api-control-plane-provider-kamaji/bin/k8s/1.25.0-darwin-arm64" go test ./... -coverprofile cover.out
github.com/clastix/cluster-api-control-plane-provider-kamaji            coverage: 0.0% of statements
github.com/clastix/cluster-api-control-plane-provider-kamaji/api/v1alpha1               coverage: 0.0% of statements
fork/exec …
```

fix: go version in Dockerfile

---

controllers/kamajicontrolplane_controller_resources.go

Closes #92.
@hexchen may I ask you for a review on this? Since it was a straightforward one I tried to implement it on my own, hope you don't mind.

fix(capi): secrets type must be cluster.x-k8s.io/secret

---

api/v1alpha1/kamajicontrolplane_types.go
config/crd/bases/controlplane.cluster.x-k8s.io_kamajicontrolplanes.yaml

Add categories to KamajiControlPlane so that they can be inspected together with other Cluster API resources and TCPs.
```
kubectl get cluster-api
kubectl get kamaji
```
Also add a short name. I chose `kjcp` because `kcp` is already taken. I'm open to change it though

feat: Add categories and short name to CRD

---

api/v1alpha1/kamajicontrolplane_types.go
config/control-plane-components.yaml
config/crd/bases/controlplane.cluster.x-k8s.io_kamajicontrolplanes.yaml
controllers/kamajicontrolplane_controller_tcp.go

When using ClusterClasses, `Version` is propagated from `cluster.Spec.Topology` into the `kamajicontrolplane.Spec` with a "v" prefix and then Kamaji complains about the wrong version format. See CAPI defaulting webhook https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/webhooks/cluster.go#L100

Accept version strings with and without a 'v' prefix

---

api/v1alpha1/kamajicontrolplane_types.go
config/control-plane-components.yaml
config/crd/bases/controlplane.cluster.x-k8s.io_kamajicontrolplanes.yaml
config/crd/bases/controlplane.cluster.x-k8s.io_kamajicontrolplanetemplates.yaml

This parameter should be optional according to this https://kamaji.clastix.io/reference/api/#tenantcontrolplanespec. Default is used  when not provided, see https://github.com/clastix/kamaji/blob/master/controllers/tenantcontrolplane_controller.go#L305 and https://github.com/clastix/kamaji/blob/master/cmd/manager/cmd.go#L259

Omit empty dataStoreName

---

controllers/kamajicontrolplane_controller_cluster_patch.go

Hello again! 
This fixes a small problem while deploying a vSphere cluster with this operator. 
`.Spec.controlPlaneEndpoint` is initially not set at all, therefore this check previously resulted in a `panic: interface conversion: interface {} is nil, not map[string]interface {}`.
This PR fixes this problem.
This is kinda a follow-up for #91, @hexchen and I are working at the same company.

fix(controller): Fix check for existing controlPlaneEndpoint in clusters

---

README.md
config/control-plane-components.yaml
config/rbac/role.yaml
controllers/kamajicontrolplane_controller_cluster_patch.go
docs/providers-ionoscloud.md

The ionoscloud provider [recently added](https://github.com/ionos-cloud/cluster-api-provider-ionoscloud/pull/171) support for externally managed control planes.
The feature is planned to be released in the v0.3.0 release of CAPIC.

feat: add ionoscloud support

---

docs/providers-ionoscloud.md

Due to https://github.com/clastix/cluster-api-control-plane-provider-kamaji/issues/126 I ended up noticing that the docs were a bit outdated.

fix(docs): update docs for ionoscloud

---

.github/workflows/e2e.yaml
.github/workflows/targetcluster-controlplane.yaml
.github/workflows/targetcluster-workers.yaml

Create new e2e github actions workflow and resolves #15 
- Running cluster-api-control-plane-provider-kamaji and validate no crashes
- Creating target cluster using cluster-api-control-plane-provider-kamaji and kubevirt infra provider
- Validate the cluster, kamajicontrolplane CR's readiness
- Validate the worker CRs like Machine, Kubevirt-pod readiness
- Fetch the kubeconfig of target cluster and install calico CNI
- Validate the readiness of target cluster node
Successfully run: https://github.com/dineshba/cluster-api-control-plane-provider-kamaji/actions/runs/11303188257/job/31439998988
Screenshot:

Add e2e tests

---

controllers/externalclusterreference_controller.go

When running the Kamaji Control Plane provider with the ExternalClusterReference feature gate enabled, a nil pointer dereference was occurring due to a missing check.

fix: nil pointer dereference for ExternalClusterReference

---

config/control-plane-components.yaml
config/manager/manager.yaml
controllers/kamajicontrolplane_controller.go
main.go
pkg/features/features.go

Support was added for the `controlPlaneEndpoint` field in #137. 
This PR builds upon that work to support making the infrastructure cluster fully optional. 
We do this by introducing a feature flag `SkipInfraClusterPatch` that when enabled will bypass patching of the infrastructure cluster.

feat: support optional infra cluster via feature flag

---

README.md
config/control-plane-components.yaml
config/rbac/role.yaml
controllers/kamajicontrolplane_controller_cluster_patch.go
docs/providers-proxmox.md

Getting ready for ionos-cloud/cluster-api-provider-proxmox#106 once it's been merged.

feat: support for the Proxmox Cluster API provider by IONOS

---

controllers/kamajicontrolplane_controller_cluster_patch.go

When deploying a kamaji cluster on Openstack I would get this error(in the capi-kamaji-controller-manager) after the TenantControlPlane had been created, initialised and being ready:
```
2024-11-13T10:34:25Z	ERROR	Reconciler error	{"controller": "kamajicontrolplane", "controllerGroup": "controlplane.cluster.x-k8s.io", "controllerKind": "KamajiControlPlane", "KamajiControlPlane": {"name":"test-kamaji-cluster-control-plane","namespace":"test-kamaji-cluster"}, "namespace": "test-kamaji-cluster", "name": "test-kamaji-cluster-control-plane", "reconcileID": "42e03cd9-c0b9-445e-ac8f-0d451ddf8e63", "error": "cannot perform PATCH update for the OpenStackCluster resource: failed to patch OpenStackCluster test-kamaji-cluster/test-kamaji-cluster: OpenStackCluster.infrastructure.cluster.x-k8s.io …
```

Fix patchOpenStackCluster spec overwrite

---

controllers/kamajicontrolplane_controller_externalreference.go

Modifications Made:
1. ExternalClusterReference not enabled should be only based on single feature flag i.e ExternalClusterReference
2. Added one more condition for CrossNamespaceReference. If CrossNamespaceReference is not enabled then only validate for namespace value match with KCP namespace.

Fix: CrossNamespace remotecluster reference is not supported

---

controllers/kamajicontrolplane_controller.go
go.mod
main.go

feat(controller): add paused resource handling and update manager setup

---

config/control-plane-components.yaml
config/manager/manager.yaml
controllers/kamajicontrolplane_controller.go
controllers/kamajicontrolplane_controller_cluster_patch.go
main.go
pkg/features/features.go

This feature request introduces a feature togglable via the Feature Flag `DynamicInfrastructureClusterPatch` which allows patching any Infrastructure Cluster specified in the CLI flag `--infrastructure-clusters` which accepts a comma-separated list of Kubernetes API object kinds.
This feature is useful for developers aiming to integrate Kamaji within their organizations where a Cluster API infrastructure provider is not public.
Upon installation, a proper RBAC must be addressed here, otherwise patching would require a `*` scope which isn't good from a threat modeling perspective.

feat: dynamic infrastructure clusters patching

---

controllers/kamajicontrolplane_controller_tcp.go

Required to address clastix/kamaji#679

fix: validating certificate subject alternative names

---

.github/workflows/ci.yaml
.github/workflows/docker-ci.yaml
.github/workflows/e2e.yaml
.github/workflows/release.yaml

Going over the [Scorecard report](https://securityscorecards.dev/viewer/?uri=github.com/clastix/cluster-api-control-plane-provider-kamaji) and fixing some things.
**Reason**
detected GitHub workflow tokens with excessive permissions
**Details**
Warn: no topLevel permission defined: .github/workflows/ci.yaml:1
Warn: no topLevel permission defined: .github/workflows/docker-ci.yaml:1
Warn: no topLevel permission defined: .github/workflows/e2e.yaml:1
Warn: no topLevel permission defined: .github/workflows/release.yaml:1
Info: no jobLevel write permissions found
I used https://app.stepsecurity.io/secureworkflow to verify the permissions as recommended in the documentation.

ci: fix token permissions

---

docs/providers-aws.md
docs/providers-azure.md
docs/providers-hetzner.md
docs/providers-nutanix.md
docs/providers-openstack.md
docs/providers-vsphere.md

Fixes #199 
- Removed `--cloud-provider=external`from apiServer args which is no longer available since Kubernetes 1.33

docs: remove deprecated flag for kube-apiserver in provider docs

---

templates/vsphere/capi-kamaji-vsphere-autoscaler-template.yaml
templates/vsphere/capi-kamaji-vsphere-class-template.yaml
templates/vsphere/capi-kamaji-vsphere-dhcp-template.yaml
templates/vsphere/capi-kamaji-vsphere-template-ccm.yaml
templates/vsphere/capi-kamaji-vsphere-template-csi.yaml
templates/vsphere/capi-kamaji-vsphere-template.yaml

remove deprecated flag for kube-apiserver in templates

---

controllers/kamajicontrolplane_controller_tcp.go

Sorry, missed this during testing. The KCP has the field but it's not on the TCP because the value gets cleared in an else block.

fix: use fallback for dnsServiceIPs

---

controllers/externalclusterreference_controller.go

We observed high memory usage in our test environment with relatively low numbers of control planes (~30) being created.
With this change the memory usage overall decreases when using ECR and it also becomes less bursty.

fix: limit ECR manager cache to TenantControlPlanes
